{
 "title": "Airgradient Native",
 "description": "Dashboard for the Airgradient One native prometheus metrics exporter. Compatible with the 3.0.6 firmware.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serial",
    "query": {
     "query": "label_values(airgradient_info,airgradient_serial_number)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Airgradient Sensor Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Airgradient Sensors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "airgradient_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Status (serial $serial)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "serial"
  },
  {
   "title": "Temperature (degrees celcius)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_temperature_degc * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_humidity_percent * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CO2 Level (Sensor: SenseAir S8)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_co2_ppm * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "{{airgradient_serial_number}}"
    }
   ]
  },
  {
   "title": "PM03 Particles / 100ml",
   "type": "stat",
   "description": "Total number of particles with a diameter of 0.3 micrometers or smaller per 100ml air",
   "gridPos": { "h": 10, "w": 2, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "particles/100ml" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm0d3_p100ml * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "PM 0.3 particles / 100ml"
    }
   ]
  },
  {
   "title": "PM1 Particle Concentration in μg / m3",
   "type": "stat",
   "description": "Total weight of particles with a diameter of 1.0 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 10, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm1_ugm3 * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "PM 1.0 μg / m3"
    }
   ]
  },
  {
   "title": "PM2.5 Particle Concentration in μg / m3",
   "type": "stat",
   "description": "Total weight of particles with a diameter of 2.5 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 10, "w": 3, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm2d5_ugm3 * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "PM 2.5 μg / m3"
    }
   ]
  },
  {
   "title": "PM10 Particle Concentration in μg / m3",
   "type": "stat",
   "description": "Total weight of particles with a diameter of 10.0 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 10, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm10_ugm3 * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "PM 10.0 μg / m3"
    }
   ]
  },
  {
   "title": "NOx Index (1=24h average)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "NOx" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_nox_index * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "{{airgradient_serial_number}} TVOC index"
    }
   ]
  },
  {
   "title": "TVOC Index (100=24h average)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "TVOC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_tvoc_index * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=\"$serial\"}",
     "legendFormat": "{{airgradient_serial_number}} TVOC index"
    }
   ]
  },
  {
   "title": "Temperature & Humidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature (degrees celcius)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "airgradient_temperature_degc * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=~\"$serial\"}",
       "legendFormat": "{{airgradient_serial_number}}"
      }
     ]
    },
    {
     "title": "Relative Humidity (%)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "airgradient_humidity_percent * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=~\"$serial\"}",
       "legendFormat": "{{airgradient_serial_number}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CO2 PPM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CO2 Level (Sensor: SenseAir S8)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "airgradient_co2_ppm * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=~\"$serial\"}",
       "legendFormat": "{{airgradient_serial_number}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Particle Pollution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM03 Particles / 100ml",
     "type": "timeseries",
     "description": "Total number of particles with a diameter of 0.3 micrometers or smaller per 100ml air",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "particles/100ml" } },
     "targets": [
      {
       "expr": "airgradient_pm0d3_p100ml * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=~\"$serial\"}",
       "legendFormat": "{{ airgradient_serial_number }} PM 0.3 particles / 100ml"
      }
     ]
    },
    {
     "title": "PM1 Particle Concentration in μg / m3",
     "type": "timeseries",
     "description": "Total weight of particles with a diameter of 1.0 micrometers or smaller, in μg / m3",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "expr": "airgradient_pm1_ugm3 * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info",
       "legendFormat": "PM 1.0 μg / m3"
      }
     ]
    },
    {
     "title": "PM2.5 Particle Concentration in μg / m3",
     "type": "timeseries",
     "description": "Total weight of particles with a diameter of 2.5 micrometers or smaller, in μg / m3",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "expr": "airgradient_pm2d5_ugm3 * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info",
       "legendFormat": "PM 2.5 μg / m3"
      }
     ]
    },
    {
     "title": "PM10 Particle Concentration in μg / m3",
     "type": "timeseries",
     "description": "Total weight of particles with a diameter of 10.0 micrometers or smaller, in μg / m3",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "expr": "airgradient_pm10_ugm3 * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info",
       "legendFormat": "PM 10.0 μg / m3"
      }
     ]
    }
   ]
  },
  {
   "title": "TVOC / NOx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "TVOC Index (100=24h average)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "TVOC" } },
     "targets": [
      {
       "expr": "airgradient_tvoc_index * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=~\"$serial\"}",
       "legendFormat": "{{sensor}} TVOC index"
      }
     ]
    },
    {
     "title": "NOx Index (1=24h average)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "NOx" } },
     "targets": [
      {
       "expr": "airgradient_nox_index * on (job,instance) group_left(airgradient_serial_number, airgradient_device_type, airgradient_library_version) airgradient_info{airgradient_serial_number=~\"$serial\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}